--
-- PostgreSQL database dump
--

\restrict BGTMRgBRKvhgcjFeXQMMOWpVjwp1vVvlimEviBO7Ucj6Cp4aEAicsA4CViSVxEG

-- Dumped from database version 17.8 (Debian 17.8-1.pgdg13+1)
-- Dumped by pg_dump version 17.8 (Debian 17.8-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Ingredient; Type: TABLE; Schema: public; Owner: mrc_user
--

CREATE TABLE public."Ingredient" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Unit" character varying(50) NOT NULL,
    "Amount" double precision NOT NULL
);


ALTER TABLE public."Ingredient" OWNER TO mrc_user;

--
-- Name: Ingredients_Id_seq; Type: SEQUENCE; Schema: public; Owner: mrc_user
--

ALTER TABLE public."Ingredient" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ingredients_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Instruction; Type: TABLE; Schema: public; Owner: mrc_user
--

CREATE TABLE public."Instruction" (
    "Id" integer NOT NULL,
    "Text" text NOT NULL,
    "Order" integer NOT NULL,
    "RecipeId" integer NOT NULL
);


ALTER TABLE public."Instruction" OWNER TO mrc_user;

--
-- Name: Instructions_Id_seq; Type: SEQUENCE; Schema: public; Owner: mrc_user
--

ALTER TABLE public."Instruction" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Instructions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Recipe; Type: TABLE; Schema: public; Owner: mrc_user
--

CREATE TABLE public."Recipe" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Author" character varying(100) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "IngredientList" integer[]
);


ALTER TABLE public."Recipe" OWNER TO mrc_user;

--
-- Name: Recipe_Id_seq; Type: SEQUENCE; Schema: public; Owner: mrc_user
--

ALTER TABLE public."Recipe" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Recipe_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Ingredient; Type: TABLE DATA; Schema: public; Owner: mrc_user
--

COPY public."Ingredient" ("Id", "Name", "Unit", "Amount") FROM stdin;
1	whole milk	cup	1
2	granulated sugar	cup	0.75
3	salt flakes	pinch	1
4	heavy cream	cup	2
5	vanilla extract	tbsp	1
6	cocoa powder, sifted	cup	0.75
7	granulated sugar	cup	0.5
8	dark brown sugar, measured packed	cup	0.34
9	vanilla extract	teaspoon	1.5
10	unsalted butter, for Buttered Pecans	tablespoons	4
11	pecans, for Buttered Pecans	cup	1
12	salt flakes, for Buttered Pecans	teaspoon	1
13	vanilla extract	tablespoon	1
14	fresh, ripe strawberries, hulled and halved (or quartered, if they are large)	cup	1.5
15	whole milk	cup	0.75
16	granulated sugar	cup	0.66
17	good quality peanut butter (not natural)	cup	1
18	granulated sugar	cup	0.34
19	vanilla extract	teaspoon	1
20	chopped Reeses Peanut Butter Cups (or 15 mini cups)	cup	1
21	heavy cream	cup	1.5
22	cocoa powder, sifted	cup	0.5
23	granulated sugar	cup	0.33
24	packed, dark brown sugar	cup	0.25
25	whole milk	cup	0.66
26	heavy cream	cup	1.5
27	mini marshmallows	cup	0.5
28	full McVities digestive biscuits (about 4), crushed	cup	0.5
29	chocolate chips, melted and reserved at room temperature	cup	0.33
30	heavy cream	cup	2
31	whole milk	cup	0.5
32	salt flakes	teaspoon	0.25
33	packed, dark brown sugar	cup	0.33
34	water	tablespoon	1
35	unsalted butter	tablespoon	2
36	large bananas, cut into 1.2 cm pieces	bananas	2
37	dark rum	tablespoons	1.5
38	fresh lemon juice	teaspoon	0.25
39	chocolate chips (bittersweet)	cup	0.33
40	toasted walnuts, roughly chopped	cup	0.5
41	whole milk	cup	2
42	granulated sugar, divided	cup	1
43	whole vanilla bean, halfed and seeds scraped	bean	1
44	large egg yolks	egg yolks	5
45	whole milk	cup	2
46	heavy cream	cup	2
47	granulated sugar, divided	cup	1
48	vanilla extract	teaspoon	1.5
49	fresh mint leaves, packed	cup	2
50	large egg yolks	egg yolks	5
51	crushed chocolate sandwich cookies (about 8)	cups	1
52	heavy cream	cup	1.5
53	granulated sugar, divided	cup	0.66
54	ground cinnamon	teaspoon	1
55	cayenne	pinch	2
56	bittersweet chocolate, roughly chopped (about 1 cup chips)	ounces	6
57	whole milk	cup	1.25
58	heavy cream	cup	1.25
59	granulated sugar, divided	cup	0.33
60	large egg yolks	egg yolks	4
61	granulated sugar	cup	0.5
62	salt flakes	teaspoon	0.25
63	water (just enough to cover sugar and make it seem like wet sand)	tablespoon	3
64	heavy cream	cup	0.25
65	unsalted butter	tablespoon	2
66	flaked sea salt, for garnish	tablespoon	1
67	water	cup	3
68	granulated sugar	cup	1.33
69	cocoa powder, sifted	cup	1.66
70	water	cup	0.66
71	granulated sugar	cup	0.66
72	grapefruit zest	tablespoon	1
73	fresh grapefruit juice	cup	2
74	Prosecco (Italian sparkling wine)	cup	0.66
75	dairy-free milk (soy, hemp, almond, rice)	cup	3
76	tapioca flour	tablespoon	2
77	granulated sugar	cup	0.66
78	granulated sugar	cup	0.66
79	light brown sugar	cup	0.33
80	coconut milk (do not use "lite")	can	2
81	water	tablespoon	3
82	honey	tablespoon	2
83	vanilla beans, split and seeds scraped	bean	2
84	whole-milk Greek yogurt	cup	3
85	vanilla extract	teaspoon	1
86	granulated sugar	cup	0.66
87	whole-milk, plain Greek yogurt	cup	2
88	granulated sugar	cup	0.5
89	mango pieces (you may use frozen mango pieces in place of fresh. Be sure they are fully thawed.)	cup	4
90	fresh lime juice (about 1/2 lime)	teaspoon	1
91	whole-milk, plain Greek yogurt	cup	2
92	milk (any fat variety)	cup	1
93	granulated sugar	cup	0.66
94	cocoa powder, sifted	cup	0.33
95	chopped chocolate or yogurt covered pretzels	cup	1
96	heavy cream	cup	1.75
97	whole milk, divided	cup	2.25
98	cornstarch	tablespoon	2
99	chocolate-hazelnuts spread	cup	1
100	chopped hazelnuts (or you may use the same amount of chopped chocolate hazelnut candies)	cup	1
101	whole milk, divided	cup	2
102	brewed espresso	cup	1
103	liquid pectin	tablespoon	1
104	plus 1 tablespoon unbleached, all-purpose flour	cup	1
105	salt flakes	teaspoon	1
106	baking soda	teaspoon	0.66
107	unsalted butter, softened (8 tbsp)	stick	1
108	packed, light brown sugar	cup	1
109	granulated sugar	cup	0.66
110	whole egg, room temperature	egg	1
111	semisweet chocolate chips (or pieces of chocolate broken up)	ounces	6
112	ice cream, slightly softened	cup	6
113	whole milk, divided	cup	2
114	vanilla extract	teaspoon	2
115	heavy cream	cup	1
116	salt flakes	teaspoon	0.25
117	large egg yolks	yolks	6
118	heavy cream	cup	0.66
119	light corn syrup	cup	0.33
120	light brown sugar, packed	cup	0.33
121	cocoa powder, sifted	cup	0.25
122	salt flakes	teaspoon	0.25
123	unsalted butter	tablespoon	2
124	semisweet chocolate, chopped	grams	170
125	salt flakes	teaspoon	0.5
126	granulated sugar	cup	0.66
127	water (enough so that the consistency when mixed with the sugar and salt is similar to wet sand)	cup	0.25
128	light corn syrup	tablespoon	1
129	heavy cream	cup	0.33
130	unsalted butter, cut into 1.2cm cubes	tablespoon	3
\.


--
-- Data for Name: Instruction; Type: TABLE DATA; Schema: public; Owner: mrc_user
--

COPY public."Instruction" ("Id", "Text", "Order", "RecipeId") FROM stdin;
1	This ice cream can easily be dressed up by adding your favorite chopped candies or sprinkles at the end of churning.	1	1
2	Makes about 4 and 1/2 cups (nine, 1/2-cup servings)	2	1
3	In a medium bowl, use a hand mixer on low speed or whisk to combine the milk, sugar and salt until the sugar is dissolved.	3	1
4	Stir in the heavy cream and vanilla extract.	4	1
5	Cover and refrigerate a minimum of 2 hours, preferably overnight.	5	1
6	Whisk mixture together again before continuing	6	1
7	Put the frozen freezer bowl into your 2 Quart ice cream maker and turn it on. Pour the mixture into the frozen freezer bowl.	7	1
8	Churn for 15 to 20 minutes. The longer you churn the firmer the consistency.	8	1
9	After churning, spoon ice cream into the container, adding mix-ins at each layer as desired.	9	1
10	Put wax paper over the top layer of ice cream to prevent freezer burn. Cover and freeze for a minimum of 2 hours. 	10	1
11	Makes about 5 cups (ten, 1/2-cup servings)	1	2
12	In a medium bowl, whisk together the cocoa powder, sugars, and salt. Add the milk and, using the mixer on low speed or a whisk, beat to combine until the cocoa, sugars and salt are dissolved.	2	2
13	Stir in the heavy cream and vanilla extract. Cover and refrigerate for a minimum of 2 hours, preferably overnight.	3	2
14	Whisk mixture together again before continuing.	4	2
15	Put the frozen freezer bowl into your 2 Quart ice cream maker and turn it on. Pour the mixture into the frozen freezer bowl.	5	2
16	Let the mixture churn for 15 to 20 minutes. The longer you churn the firmer the consistency.	6	2
17	After churning, spoon ice cream into the container, adding mix-ins at each layer as desired.	7	2
18	Put wax paper over the top layer of ice cream to prevent freezer burn. Cover and freeze for a minimum of 2 hours.	8	2
19	The butter used to toast the pecans can be saved and used over pancakes or waffles.	1	3
20	Makes about 5 cups (ten, 1/2-cup servings)	2	3
21	Prepare the Buttered Pecans. Melt the butter in a medium frypan. Add the pecans and 1 teaspoon of salt.	3	3
22	Cook over medium-low heat until the pcans are toasted and golden, stirring frequently, about 6 to 8 minutes.	4	3
23	Remove from the heat, strain and reserve the pecans, allowing them to chill. The butter can be for another use.	5	3
24	Prepare the Ice Cream Base. In a medium bowl, use a mixer on low speed or whisk to bomcine the milk, sugar, and a pinch of salt until the sugar is dissolved.	6	3
25	Stir in the heavy cream and vanilla extract. Cover and refrigerate a minimum of 2 hours, preferably overnight.	7	3
26	Whisk mixture together again before continuing.	8	3
27	Put the frozen freezer bowl into your 2 Quart ice cream maker and turn it on. Pour the milk/cream mixture into the frozen freezer bowl and churn.	9	3
28	Churn for 15 to 20 minutes. The longer you churn the firmer the consistency.	10	3
29	After churning, spoon ice cream into the container, adding pecanss at each layer as desired.	11	3
30	Put wax paper over the top layer of ice cream to prevent freezer burn. Cover and freeze for a minimum of 2 hours.	12	3
31	Best made when strawberries are in peak season, this ice crema is light, sweet, and fluffy.	1	4
32	Makes about 5 cups (ten, 1/2-cup servings).	2	4
33	Put the strawberries into a bowl of a food processor fitted with the chopping blade. Pluse strawverries until rough/fine chopped (depending on prefernence).	3	4
34	In a medium bowl, use a mixer on low speed or whisk to combine the milk, sugar,and salt until the sugar is dissolved. Stir in the heavy cream and vanilla extract.	4	4
35	Stir in the reserved strawverries with all juices. Cover and refrigerate a minimum of 2 hours, preferably overnight.	5	4
36	Whisk mixture together again before continuing.	6	4
37	Put the frozen freezer bowl into your 2 Quart ice cream maker and turn it on. Pour the mixture into the frozen freezer bowl and churn.	7	4
38	Churn for 15 to 20 minutes. The longer you churn the firmer the consistency.	8	4
39	After churning, spoon ice cream into the container, adding strawberries at each layer as desired.	9	4
40	This ice cream freezes more quickly than others, so keep a close eye on it to allow enough time to add decadent peanut butter cups.	1	5
41	Makes about 5 cups (ten, 1/2-cup servings).	2	5
42	In amedium bowl, mix on low speed to combine the peanut butter and sugar until smooth. Add the milk and mix on low speed until the sugar is dissolved.	3	5
43	Stir in the heavy cream and vanilla extract. Cover and refrigerate a minimum of 2 hours, preferably overnight.	4	5
44	Whisk mixture together again before continuing.	5	5
45	Put the frozen freezer bowl into your 2 Quart ice cream maker and turn it on. Pour the mixture into the frozen freezer bowl and churn.	6	5
46	Churn for 8 to 10 minutes. The longer you churn the firmer the consistency.	7	5
47	After churning, spoon ice cream into the container, adding chopped Reeses Peanut Butter Cups (or 15 mini cups) at each layer as desired.	8	5
48	Put wax paper over the top layer of ice cream to prevent freezer burn. Cover and freeze for a minimum of 2 hours.	9	5
49	In a medium saucepan, combine 1 and 3/4 cups of the milk, heavy cream, vanilla extract, and salt over medium heat. In a small bowl, mix together well the remaining ilk with the cornstarch and reserve.	1	21
50	While the cream mixture is heating, whisk the egg yolks and sugar together until pale and thick.	2	21
51	Once the cream mixture comes to a simmer, stir in the milk/cornstarch mixture and continue to stir over heat for an additional 5 minutes, being sure mixture does not come to a boil.	3	21
52	Whisking continuously at the same time, very slowly pour all of the hot liquid into the yolk/sugar mixture. Return mixture back to the saucepan over heat, whisk for about 5 minutes and then return to mixing bowl. Cool to room temperature. Cover and refrigerate a minimum of 2 hours, preferably overnight. Whisk mixture together again before pouring into the Cool Scoops (TM)	4	21
53	Turn on the Cuisinart ice crema maker; pour the mixture into the frozen freezer bowl and let mix until thickened, about 15 to 20 minutes. The gelato will have a soft, creamy texture. If a firmer consistency is desired, transfer to an airtight container and place in freezer for about 2 hours. Remove from freezer about 15 minutes before serving.	5	21
54	In a medium saucepan, combine cream and 1 and 1/2 cups of the milk. Set over medium/medium-low heat and bring to a simmer.	1	19
55	While creamin/milk mixture is heating, put the remaining milk, sugar, cornstarch and salt into a small-medium mixing bowl. Whisk to combine.	2	19
56	Once milk/cream mixture comes to a simmer, add the milk/sugar mixture and stir until fully combined. Slowly whisk in the chocolate-hazelnut spread. While still set over medium/medium-low heat, continuously stir until mixture boils and thickens to where it can coat the back of a spoon (this will take about 10 to 15 minutes, depending on the type of pan and stove being used.	3	19
57	Turn on the Cuisinart ice cream maker and pour the mixture into the frozen freezer bowl and let mix until thickened, about 15 to 20 minutes. About 5 minutes before the mixture has finished, add the chopped hazelnuts/candies through the opening. The gelato will have a soft, creaming texture. If a firmer cosistency is desired, transfer to an airtight container and place in freezer for about 2 hours. Remove from freezer about 15 minutes before serving.	5	19
58	Remove pan from heat, strain and cool to room temperature. Cover and refrigerate a minimmum of 2 hours, preferably overnight. Whisk mixture together again before pouring into the ice cream maker.	4	19
59	In a medium saucepan, combine 1 and 1/2 cups of the milk adn the cream. Set over medium/medium-low heat and bring to a simmer.	1	20
60	While cream/milk mixture is heating, put the remainint milk, espressor, sugar, corstarch, and salt ito a small-medium mixing bowl. Whisk to combine.	2	20
61	Once the milk/cream mixture comes to a simmer, add the milk/sugar mixture and stir until fully combined. While still set over medium/medium-low heat, stir continuously until mixture boils and thickens to where it can coat the back of a spoon (this will take about 15 minutes, depending on the stove being used).	3	20
62	Remove pan from heat, stir in pectin, strain and cool to room temperature. Cover and refrigerate a minimum of 2 hours, preferably overnight. Whisk mixture together again before pouring into the ice cream maker.	4	20
63	Turn on the ice crema maker and pour the mixture into the frozen freezer bowl and let mix until thickened, about 15 to 20 minutes. The gelato will have a soft, creamy texture. If a firmer consistency is desired, transfer to an airtight container and place in freezer for about 2 hours. Remove from freezer about 15 minutes before serving.	5	20
64	In a large mixing bowl, whisk the yogurt, milk, sugar, cocoa powder, salt, and vanilla extract together. Whisk unti the sugar has dissolved. Cover and refrigerate a minimum of 2 hours, preferably overnight. Whisk mixture together again before pouring into the ice cream container.	1	18
65	Turn on the ice cream maker and pour the mixture into the frozen freezer bowl and let it mix until thickened, about 15 to 20 minutes. When the frozen yogurt is almost done churning, add the chopped pretzels through the opening at the top of the ice cream maker. The frozen yogurt will have a soft, creamy texture. If a firmer consistency is desired, transfer the frozen yogurt to an airtight container and place in freezer for about 2 hours. Remove from freezer about 15 minutes before serving.	2	18
66	Mix all ingredients together very well until there are no clumps. (A blender or hand blender is a great tool for this. Simply put all ingredients ito the blender jar and blend on low. If using a hand blender, combine all ingredients into a large mixing bowl and blend until smooth.) Cover and refrigerate a minimum of 2 hours, preferably overnight. Whisk mixture together again before pouring into the ice cream maker.	1	15
67	Turn on the ice cream maker and pour the mixture into the frozen freezer bowl and let mix until thickened, about 20 to 25 minutes. The ice cream will have a soft, creamy texture. If a firmer consistency is desired, transfer to an airtight container and place in freezer for about 2 hours. Remove from freezer about 15 minutes before serving.	2	15
68	Put the water, honey, and vanilla beans into a small saucepan. Over medium-low heat, bring mixture to a boil, then simmer until reduced by about half. Strain (discarding the vanilla pods); reserve.	1	16
69	In a large bowl, whisk the yogurt, reserved honey/water/vanilla reduction, vanilla extract, sugar, and salt together. Whisk until the sugar has dissolved. Cover and refrigerate a minimum of 2 hours, preferably overnight. Whisk mixture together again before pouring into the ice cream maker.	2	16
70	Turn on the ice cream maker and pour the mixture into the frozen freezer bowl and let mix until thickened, about 8 to 10 minutes. The frozen yogurt will have a soft, creamy texture. If a firmer consistency is desired, transfer the frozen yogurt to an airtight container and place in freezer for about 2 hours. Remove from freezer about 15 minutes before serving.	3	16
71	In a large mixing bowl, whisk together yogurt, salt, ad sugar together; reserve.	1	17
72	Using a blender, puree the mangoes with the lime juice and 1 cup of the yogurt mixture. Combine with the remaining yogurt/stugar mixture. Cover and refrigerate a minimum of 2 hours, preferably overnight. Whisk together again before pouring into the ice cream maker.	2	17
73	Turn on the ice cream maker and pour the mixture into the frozen freezer bowl and let mix until thickened, about 15 to 20 minutes. The frozen yogurt will have a soft, creamy texture. If a firmer consistency is desired, transfer to frozen yogurt to an airtight container and place in freezer for about 2 hours. Remove from freezer about 15 minutes before serving.	3	17
74	In a large mixing bowl, whisk together yogurt, salt, and sugar together; reserve.	1	17
\.


--
-- Data for Name: Recipe; Type: TABLE DATA; Schema: public; Owner: mrc_user
--

COPY public."Recipe" ("Id", "Name", "Author", "CreatedDate", "IngredientList") FROM stdin;
9	Fresh Mint and Chocolate Cookies Ice Cream	Cuisinart	2024-01-01 00:00:00+00	\N
10	Mexican-Style Chocolate Ice Cream	Cuisinart	2024-01-01 00:00:00+00	\N
11	Salted Caramel Ice Cream	Cuisinart	2024-01-01 00:00:00+00	\N
12	Dark Chocolate Sorbet	Cuisinart	2024-01-01 00:00:00+00	\N
13	Grapefruit and Prosecco Sorbet	Cuisinart	2024-01-01 00:00:00+00	\N
14	Dairy-Free Vanilla Ice Cream	Cuisinart	2024-01-01 00:00:00+00	\N
15	Coconut-Chocolate Ice Cream	Cuisinart	2024-01-01 00:00:00+00	\N
16	Rich Vanilla Frozen Yogurt	Cuisinart	2024-01-01 00:00:00+00	\N
17	Mango Frozen Yogurt	Cuisinart	2024-01-01 00:00:00+00	\N
18	Chocolate-Pretzel Frozen Yogurt	Cuisinart	2024-01-01 00:00:00+00	\N
19	Chocolate-Hazelnut Gelato	Cuisinart	2024-01-01 00:00:00+00	\N
20	Espresso Gelato	Cuisinart	2024-01-01 00:00:00+00	\N
21	Custard Gelato	Cuisinart	2024-01-01 00:00:00+00	\N
1	Simple Vanilla Ice Cream	Cuisinart	2024-01-01 00:00:00+00	{1,2,3,4,5}
2	Simple Chocolate Ice Cream	Cuisinart	2024-01-01 00:00:00+00	{6,7,8,1,3,4,9}
3	Butter Pecan Ice Cream	Cuisinart	2024-01-01 00:00:00+00	{10,11,12,1,2,3,4,5}
4	Fresh Strawberry Ice Cream	Cuisinart	2024-01-01 00:00:00+00	{14,15,16,3,9,21}
5	Peanut Butter Cup Ice Cream	Cuisinart	2024-01-01 00:00:00+00	{17,18,1,4,5,20}
7	Banana Walnut Chip Ice Cream	Cuisinart	2024-01-01 00:00:00+00	{4,31,19,32,33,34,35,36,37,38,39,40}
6	S'mores Ice Cream	Cuisinart	2024-01-01 00:00:00+00	{22,23,24,3,25,26,9,27,28,29}
8	Vanilla Bean Ice Cream	Cuisinart	2024-01-01 00:00:00+00	{9,44,43,3,42,30,41}
\.


--
-- Name: Ingredients_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: mrc_user
--

SELECT pg_catalog.setval('public."Ingredients_Id_seq"', 130, true);


--
-- Name: Instructions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: mrc_user
--

SELECT pg_catalog.setval('public."Instructions_Id_seq"', 74, true);


--
-- Name: Recipe_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: mrc_user
--

SELECT pg_catalog.setval('public."Recipe_Id_seq"', 21, true);


--
-- Name: Ingredient PK_Ingredients; Type: CONSTRAINT; Schema: public; Owner: mrc_user
--

ALTER TABLE ONLY public."Ingredient"
    ADD CONSTRAINT "PK_Ingredients" PRIMARY KEY ("Id");


--
-- Name: Instruction PK_Instructions; Type: CONSTRAINT; Schema: public; Owner: mrc_user
--

ALTER TABLE ONLY public."Instruction"
    ADD CONSTRAINT "PK_Instructions" PRIMARY KEY ("Id");


--
-- Name: Recipe PK_Recipe; Type: CONSTRAINT; Schema: public; Owner: mrc_user
--

ALTER TABLE ONLY public."Recipe"
    ADD CONSTRAINT "PK_Recipe" PRIMARY KEY ("Id");


--
-- Name: IX_Instructions_RecipeId; Type: INDEX; Schema: public; Owner: mrc_user
--

CREATE INDEX "IX_Instructions_RecipeId" ON public."Instruction" USING btree ("RecipeId");


--
-- Name: Instruction FK_Instructions_Recipe_RecipeId; Type: FK CONSTRAINT; Schema: public; Owner: mrc_user
--

ALTER TABLE ONLY public."Instruction"
    ADD CONSTRAINT "FK_Instructions_Recipe_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES public."Recipe"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict BGTMRgBRKvhgcjFeXQMMOWpVjwp1vVvlimEviBO7Ucj6Cp4aEAicsA4CViSVxEG

