/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipeCatalogueRouteImport } from './routes/recipe-catalogue'
import { Route as MainRouteImport } from './routes/_main'
import { Route as RecipeCatalogueIndexRouteImport } from './routes/recipe-catalogue/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as RecipeCatalogueMyRecipesRouteImport } from './routes/recipe-catalogue/my-recipes'
import { Route as RecipeCatalogueCatalogueRouteImport } from './routes/recipe-catalogue/catalogue'
import { Route as MainRecipesRouteImport } from './routes/_main/recipes'
import { Route as MainMenuRouteImport } from './routes/_main/menu'
import { Route as MainMembershipRouteImport } from './routes/_main/membership'
import { Route as MainContactRouteImport } from './routes/_main/contact'
import { Route as MainAboutRouteImport } from './routes/_main/about'

const RecipeCatalogueRoute = RecipeCatalogueRouteImport.update({
  id: '/recipe-catalogue',
  path: '/recipe-catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeCatalogueIndexRoute = RecipeCatalogueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipeCatalogueRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const RecipeCatalogueMyRecipesRoute =
  RecipeCatalogueMyRecipesRouteImport.update({
    id: '/my-recipes',
    path: '/my-recipes',
    getParentRoute: () => RecipeCatalogueRoute,
  } as any)
const RecipeCatalogueCatalogueRoute =
  RecipeCatalogueCatalogueRouteImport.update({
    id: '/catalogue',
    path: '/catalogue',
    getParentRoute: () => RecipeCatalogueRoute,
  } as any)
const MainRecipesRoute = MainRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => MainRoute,
} as any)
const MainMenuRoute = MainMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MainRoute,
} as any)
const MainMembershipRoute = MainMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => MainRoute,
} as any)
const MainContactRoute = MainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/recipe-catalogue': typeof RecipeCatalogueRouteWithChildren
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/membership': typeof MainMembershipRoute
  '/menu': typeof MainMenuRoute
  '/recipes': typeof MainRecipesRoute
  '/recipe-catalogue/catalogue': typeof RecipeCatalogueCatalogueRoute
  '/recipe-catalogue/my-recipes': typeof RecipeCatalogueMyRecipesRoute
  '/recipe-catalogue/': typeof RecipeCatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/membership': typeof MainMembershipRoute
  '/menu': typeof MainMenuRoute
  '/recipes': typeof MainRecipesRoute
  '/recipe-catalogue/catalogue': typeof RecipeCatalogueCatalogueRoute
  '/recipe-catalogue/my-recipes': typeof RecipeCatalogueMyRecipesRoute
  '/': typeof MainIndexRoute
  '/recipe-catalogue': typeof RecipeCatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/recipe-catalogue': typeof RecipeCatalogueRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/membership': typeof MainMembershipRoute
  '/_main/menu': typeof MainMenuRoute
  '/_main/recipes': typeof MainRecipesRoute
  '/recipe-catalogue/catalogue': typeof RecipeCatalogueCatalogueRoute
  '/recipe-catalogue/my-recipes': typeof RecipeCatalogueMyRecipesRoute
  '/_main/': typeof MainIndexRoute
  '/recipe-catalogue/': typeof RecipeCatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipe-catalogue'
    | '/about'
    | '/contact'
    | '/membership'
    | '/menu'
    | '/recipes'
    | '/recipe-catalogue/catalogue'
    | '/recipe-catalogue/my-recipes'
    | '/recipe-catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/membership'
    | '/menu'
    | '/recipes'
    | '/recipe-catalogue/catalogue'
    | '/recipe-catalogue/my-recipes'
    | '/'
    | '/recipe-catalogue'
  id:
    | '__root__'
    | '/_main'
    | '/recipe-catalogue'
    | '/_main/about'
    | '/_main/contact'
    | '/_main/membership'
    | '/_main/menu'
    | '/_main/recipes'
    | '/recipe-catalogue/catalogue'
    | '/recipe-catalogue/my-recipes'
    | '/_main/'
    | '/recipe-catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  RecipeCatalogueRoute: typeof RecipeCatalogueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recipe-catalogue': {
      id: '/recipe-catalogue'
      path: '/recipe-catalogue'
      fullPath: '/recipe-catalogue'
      preLoaderRoute: typeof RecipeCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe-catalogue/': {
      id: '/recipe-catalogue/'
      path: '/'
      fullPath: '/recipe-catalogue/'
      preLoaderRoute: typeof RecipeCatalogueIndexRouteImport
      parentRoute: typeof RecipeCatalogueRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/recipe-catalogue/my-recipes': {
      id: '/recipe-catalogue/my-recipes'
      path: '/my-recipes'
      fullPath: '/recipe-catalogue/my-recipes'
      preLoaderRoute: typeof RecipeCatalogueMyRecipesRouteImport
      parentRoute: typeof RecipeCatalogueRoute
    }
    '/recipe-catalogue/catalogue': {
      id: '/recipe-catalogue/catalogue'
      path: '/catalogue'
      fullPath: '/recipe-catalogue/catalogue'
      preLoaderRoute: typeof RecipeCatalogueCatalogueRouteImport
      parentRoute: typeof RecipeCatalogueRoute
    }
    '/_main/recipes': {
      id: '/_main/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof MainRecipesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/menu': {
      id: '/_main/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MainMenuRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/membership': {
      id: '/_main/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MainMembershipRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainContactRoute: typeof MainContactRoute
  MainMembershipRoute: typeof MainMembershipRoute
  MainMenuRoute: typeof MainMenuRoute
  MainRecipesRoute: typeof MainRecipesRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainContactRoute: MainContactRoute,
  MainMembershipRoute: MainMembershipRoute,
  MainMenuRoute: MainMenuRoute,
  MainRecipesRoute: MainRecipesRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface RecipeCatalogueRouteChildren {
  RecipeCatalogueCatalogueRoute: typeof RecipeCatalogueCatalogueRoute
  RecipeCatalogueMyRecipesRoute: typeof RecipeCatalogueMyRecipesRoute
  RecipeCatalogueIndexRoute: typeof RecipeCatalogueIndexRoute
}

const RecipeCatalogueRouteChildren: RecipeCatalogueRouteChildren = {
  RecipeCatalogueCatalogueRoute: RecipeCatalogueCatalogueRoute,
  RecipeCatalogueMyRecipesRoute: RecipeCatalogueMyRecipesRoute,
  RecipeCatalogueIndexRoute: RecipeCatalogueIndexRoute,
}

const RecipeCatalogueRouteWithChildren = RecipeCatalogueRoute._addFileChildren(
  RecipeCatalogueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  RecipeCatalogueRoute: RecipeCatalogueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
